FileVersion = 1
LastConfig = "Release"
LastPlatform = "Win64"
RecentFilesList = ["src\\lib\\Chunks.bf", "src\\lib\\Simulation.bf", "src\\GameApp.bf", "Disassembly", "c:\\Program Files\\BeefLang\\BeefLibs\\Atma.Framework\\src\\Atma.Common\\src\\Systems\\Time.bf", "src\\Particles.bf", "src\\Program.bf", "d:\\A01\\_work\\6\\s\\src\\vctools\\crt\\vcstartup\\src\\misc\\amd64\\chkstk.asm", "c:\\Program Files\\BeefLang\\BeefLibs\\corlib\\src\\Random.bf", "c:\\Program Files\\BeefLang\\BeefLibs\\Atma.Framework\\src\\Atma.Common\\src\\Math\\rect.bf", "Disassembly", "c:\\Program Files\\BeefLang\\BeefLibs\\Atma.Framework\\src\\Atma.Common\\src\\Math\\aabb2.bf", "d:\\A01\\_work\\6\\s\\src\\vctools\\crt\\vcruntime\\src\\string\\amd64\\memcpy.asm", "c:\\Program Files\\BeefLang\\BeefLibs\\Atma.Framework\\src\\Atma.Entities\\src\\Entity.bf", "Disassembly", "Disassembly", "c:\\Program Files\\BeefLang\\BeefLibs\\SDL2\\src\\SDLApp.bf"]

[MainWindow]
X = 64
Y = 26
Width = 1200
Height = 1024
ShowKind = "Maximized"

[MainDockingFrame]
Type = "DockingFrame"
SplitType = 2

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 350.0
RequestedHeight = 200.0
SizePriority = 200.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 549.0
RequestedHeight = 200.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Workspace"
TabWidth = 115.0
Type = "ProjectPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
IsFillWidget = true
Permanent = true
RequestedWidth = 1367.0
RequestedHeight = 150.0
SizePriority = 1367.0
DefaultDocumentsTabbedView = true
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Time.bf"
TabWidth = 83.0
Type = "SourceViewPanel"
FilePath = "c:\\Program Files\\BeefLang\\BeefLibs\\Atma.Framework\\src\\Atma.Common\\src\\Systems\\Time.bf"
CursorPos = 5682
VertPos = 1815.0
ProjectName = "Atma.Common"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "chkstk.asm"
TabWidth = 102.0
Type = "SourceViewPanel"
FilePath = "d:\\A01\\_work\\6\\s\\src\\vctools\\crt\\vcstartup\\src\\misc\\amd64\\chkstk.asm"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Random.bf"
TabWidth = 104.0
Type = "SourceViewPanel"
FilePath = "c:\\Program Files\\BeefLang\\BeefLibs\\corlib\\src\\Random.bf"
CursorPos = 5212
VertPos = 2475.0
ProjectName = "corlib"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Disassembly"
TabWidth = 122.0
Type = "DisassemblyPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "rect.bf"
TabWidth = 67.0
Type = "SourceViewPanel"
FilePath = "c:\\Program Files\\BeefLang\\BeefLibs\\Atma.Framework\\src\\Atma.Common\\src\\Math\\rect.bf"
CursorPos = 1636
VertPos = 1590.0
ProjectName = "Atma.Common"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Program.bf"
TabWidth = 96.0
Type = "SourceViewPanel"
FilePath = "src\\Program.bf"
CursorPos = 336
VertPos = 135.0
ProjectName = "BeefSand"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Entity.bf"
TabWidth = 76.0
Type = "SourceViewPanel"
FilePath = "c:\\Program Files\\BeefLang\\BeefLibs\\Atma.Framework\\src\\Atma.Entities\\src\\Entity.bf"
CursorPos = 3861
ProjectName = "Atma.Entities"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GameApp.bf"
TabWidth = 103.0
Type = "SourceViewPanel"
FilePath = "src\\GameApp.bf"
CursorPos = 3785
VertPos = 315.0
ProjectName = "BeefSand"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Chunks.bf"
TabWidth = 86.0
Type = "SourceViewPanel"
FilePath = "src\\lib\\Chunks.bf"
CursorPos = 2856
VertPos = 945.0
ProjectName = "BeefSand"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Particles.bf"
TabWidth = 93.0
Type = "SourceViewPanel"
FilePath = "src\\Particles.bf"
CursorPos = 1132
VertPos = 540.0
ProjectName = "BeefSand"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Simulation.bf"
TabWidth = 105.0
Type = "SourceViewPanel"
FilePath = "src\\lib\\Simulation.bf"
CursorPos = 2154
VertPos = 1170.0
ProjectName = "BeefSand"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Profile"
TabWidth = 87.0
Type = "ProfilePanel"

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 248.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Find Results"
TabWidth = 119.0
Type = "FindResultsPanel"

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Threads"
TabWidth = 97.0
Type = "ThreadPanel"

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Call Stack"
TabWidth = 105.0
Type = "CallStackPanel"

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Immediate"
TabWidth = 111.0
Type = "ImmediatePanel"

[[MainDockingFrame.DockedWidgets.Tabs]]
Active = true
TabLabel = "Output"
TabWidth = 90.0
Type = "OutputPanel"

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Memory"
TabWidth = 99.0
Type = "MemoryPanel"
AutoResize = "Auto_Mul8"
RequestedWidth = 300.0

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Watch"
TabWidth = 86.0
Type = "WatchPanel"
Columns = [{Width = 208.0}, {Width = 208.0}, {Width = 208.0}]
Items = [""]

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Auto"
TabWidth = 77.0
Type = "AutoWatchPanel"
Columns = [{Width = 208.0}, {Width = 290.0}, {Width = 208.0}]
